include:
  - project: aphl_aims/devsecops/centralized-cicd
    ref: stable
    file:
      - gitlab-ci-templates/iam-oidc/aws-assume.yaml

stages:
  - build

variables:
  AWS_DEFAULT_REGION: us-east-1
  ECR_REPO: kds/kds-portal
  DOCKER_HOST: "tcp://docker:2375"

.build_setup:
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://gitlab.com
  tags:
    - saas-linux-large-amd64
  image: docker:26
  services:
    - name: docker:26-dind
  before_script:
    - apk add aws-cli

.build_and_push:
  script:
    - export AWS_ACCOUNT_ID=${TARGET_AWS_ACCOUNT_ID}
    - !reference [.assume_role]
    - ECR_REGISTRY="${TARGET_AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION |
        docker login --username AWS --password-stdin $ECR_REGISTRY
    - IMAGE="${ECR_REGISTRY}/${ECR_REPO}:${CI_COMMIT_TAG}"
    - docker build -t "$IMAGE" .
    - docker push "$IMAGE"

Build and push to sandbox:
  stage: build
  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'
  variables:
    TARGET_AWS_ACCOUNT_ID: '703861148810'
  extends:
    - .build_setup
    - .build_and_push
